---
- hosts: example
  become: true
  tasks:
    - name: "Install pip"
      yum: name=python-pip state=present

    - name: "update apt-get cache"
      pip: name=docker-py 

    - name:  "INstall Docker"
      yum: name=docker state=present

    - name: Ensure service is enabled
      command: service docker restart
    - name: "create directory for dockerfile"
      file:
        path: /home/desktop/Dockerfile
        state: directory
        mode: 0777
    - name: "copying jdk"
      copy: src=/home/mkundanapalli/ansible/jdk/Dockerfile  dest=/home/Dockerfile/

    - name: "build jdk from Dockerfile"
      docker_image:
        name: jdk
        path: /home/Dockerfile
        state: build
    - name: "Running container"
      docker_container:
        name: jdk
        image: jdk
        state: started
    - name: Check if container is running
      shell: docker ps

    - name: "Copying mysql"
      file:
        path: /home/mysql
        state: directory
        mode: 0777
    - name: "copy mysql"
      copy: src=/home/mkundanapalli/ansible/mysql_test/Dockerfile dest=/home/mysql/

    - name: "build mysql from Dockerfile"
      docker_image:
        name: mysql
        path: /home/mysql
        state: build
    - name: "Running container"
      docker_container:
        name: mysql
        image: mysql
        state: started
    - name: "Check if container is running"
      shell: docker ps       
